[package]
name = "views"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gpui.workspace = true
i18n.workspace = true
icons.workspace = true
input.workspace = true
router.workspace = true
ui.workspace = true
state.workspace = true
log.workspace = true
penumbra-mtk.workspace = true