[package]
name = "sonora"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
env_logger.workspace = true
gpui.workspace = true
gpui_platform.workspace = true
i18n.workspace = true
icons.workspace = true
log.workspace = true
router.workspace = true
state.workspace = true
ui.workspace = true
views.workspace = true

[build-dependencies]
embed.workspace = true

[target.'cfg(windows)'.build-dependencies]
winresource.workspace = true